# Generated by Django 2.1.1 on 2018-09-25 22:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_key', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game_time', models.BigIntegerField(default=0)),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent1', to='game_app.MultiMove')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent2', to='game_app.MultiMove')),
            ],
        ),
        migrations.CreateModel(
            name='MultiSol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abandoned', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_pieces', models.IntegerField()),
                ('time_taken', models.BigIntegerField()),
                ('connected_players', models.IntegerField(default=0)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='multimove',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.MultiSol'),
        ),
        migrations.AddField(
            model_name='multimove',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
